apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "disaster-server.fullname" . }}
  labels:
    {{- include "disaster-server.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.configs.configYaml | indent 4 }}
