server:
  host: "0.0.0.0"
  port: 8080
  env: "dev"
  namespace: disaster-system

log:
  level: debug

jwt:
  secret: "change-me-generate-a-strong-secret"
  timeout: 24h
  access_expire: 24h
  refresh_expire: 168h

swagger:
  enabled: true

license:
  enabled: true
  namespace: ""
  caPath: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
